# Generated by Django 3.1.7 on 2021-03-05 18:06

import booklibrary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendbook',
            name='return_date',
            field=models.DateField(null=True, verbose_name='Fecha de devolucion'),
        ),
        migrations.AlterField(
            model_name='lendbook',
            name='lend_date',
            field=models.DateField(validators=[booklibrary.models.validate_lend], verbose_name='Hasta que fecha'),
        ),
        migrations.AlterField(
            model_name='lendbook',
            name='status',
            field=models.CharField(choices=[('P', 'Prestado'), ('D', 'Devuelto'), ('N', 'NoDevuelto')], default='D', max_length=1, verbose_name='Estado'),
        ),
    ]
