# Generated by Django 3.1.7 on 2021-03-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0002_auto_20210305_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendbook',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de devolucion'),
        ),
    ]
